### ISSUE TITLE
Uncaught TypeError: $this.$picker.daterangepicker is not a function

### ISSUE THREAD

**Issue by itaibaruch** [skratchdot/react-bootstrap-daterangepicker#42]
Hi,

I just install this plugin, and i can't get rid off this error:
`Uncaught TypeError: $this.$picker.daterangepicker is not a function`

my setup is :
"dependencies": {
    "bootstrap": "^3.3.5",
    "history": "^1.12.5",
    "intl": "^1.0.1",
    "jquery": "^2.1.4",
    "jquery-ui": "^1.10.5",
    "moment": "^2.10.6",
    "react": "^0.14.0",
    "react-addons": "^0.9.0",
    "react-addons-test-utils": "^0.14.0",
    "react-addons-update": "^0.14.0",
    "react-bootstrap": "^0.27.2",
    "react-bootstrap-daterangepicker": "^1.0.2",
    "react-dom": "^0.14.0",
    "react-gravatar": "^2.1.0",
    "react-intl": "^1.2.1",
    "react-router": "^1.0.0-rc3"
  },

'use strict'

var React = require('react');
var moment = require('moment');
var DateRangePicker = require('react-bootstrap-daterangepicker');

var DateRange = React.createClass({
    getInitialState: function () {
        return {
            ranges: {
                'Today': [moment(), moment()],
                'Yesterday': [moment().subtract(1, 'days'), moment().subtract(1, 'days')],
                'Last 7 Days': [moment().subtract(6, 'days'), moment()],
                'Last 30 Days': [moment().subtract(29, 'days'), moment()],
                'This Month': [moment().startOf('month'), moment().endOf('month')],
                'Last Month': [moment().subtract(1, 'month').startOf('month'), moment().subtract(1, 'month').endOf('month')]
            },
            startDate: moment().subtract(29, 'days'),
            endDate: moment()
        };
    },
    handleEvent: function (event, picker) {
        this.setState({
            startDate: picker.startDate,
            endDate: picker.endDate
        });
    },
    render: function() {
        var start = this.state.startDate.format('YYYY-MM-DD');
        var end = this.state.endDate.format('YYYY-MM-DD');
        var label = start + ' - ' + end;
        if (start === end) {
            label = start;
        }
        return (
            <div>
                <DateRangePicker 
                    startDate={this.state.startDate} 
                    endDate={this.state.endDate} 
                    ranges={this.state.ranges} 
                    onEvent={this.handleEvent}>
                    <button className="btn btn-default selected-date-range-btn" style={{width:'100%'}}>
                        <div className="pull-left">
                            icon
                        </div>
                        <div className="pull-right">
                            <span>
                                {label}
                            </span>
                            <span className="caret"></span>
                        </div>
                    </button>
                </DateRangePicker>
            </div>
        );
    }
});
module.exports = DateRange;

can someone tell me what wrong, thanks.

**Comment by skratchdot** [comment]
Someone else reported this, but the only time I was able to reproduce an error like this was back in the v0.x versions when only jQuery v1.x was working (and not jQuery v2.x).

Are you using your DateRange class multiple times on a page, or is there only 1 instance?  That's the only place I can think of this being an issue.  The code that is erroring is here: 

https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/3256217dc04e09579fc369518763ed7b70b2afa2/lib/index.js#L53

Are you using server-side rendering?

I want to try to change `var $ = require('jquery');` to `window.jQuery = require('jquery')` to see if that fixes things (and replacing line 53's `$(this.refs.picker)` with `window.jQuery(this.refs.picker)`.

**Comment by skratchdot** [comment]
see #41

**Comment by itaibaruch** [comment]
Hi @skratchdot,
replacing  $   with  window.jQuery  do the fix for me.
thank you very much!

**Comment by skratchdot** [comment]
@itaibaruch - thanks for testing. I've published a new version that *hopefully* fixes this issue: 1.0.3

**Comment by mateuszpalyz** [comment]
@itaibaruch I've got exactly the same problem with version 1.0.3, everything was fine on 1.0.2

**Comment by skratchdot** [comment]
@mateuszpalyz - sorry about this.  Do you have an example page where I can look at this (and hopefully debug it)?  If not a live example, some code I can run locally that reproduces it?

**Comment by mateuszpalyz** [comment]
@skratchdot here is a sample app with the error https://github.com/mateuszpalyz/daterangepicker-example again all is fine with 1.0.2

**Comment by skratchdot** [comment]
@mateuszpalyz - Thanks a lot!  I'm able to re-produce now.  Funny thing is: when I run your app in Firefox (localhost:3000)- it works (i.e. clicking on the text opens the date range picker).  I see an error in the console (jQuery is undefined).  When I run your app in Chrome, I see the error listed here- and the daterangepicker doesn't work.  I need to leave for a bit, but can look into this later today.  It's definitely something with the way jQuery is being included in the different modules (and on the page).

**Comment by Aldredcz** [comment]
@skratchdot I got the same error - 1.0.2 working, 1.0.3 error. Using webpack. If you need any additional info, let me know.

**Comment by skratchdot** [comment]
Ok. I re-published v1.0.2 as v1.0.4 until I find a fix for v1.0.3. Thanks for the information @Aldredcz !

**Comment by brad** [comment]
I worked around this by adjusting the version of jQuery in my own `package.json` file to 1.11.3

**Comment by skratchdot** [comment]
Thanks @brad!  I wonder if moving `jquery` to the `peerDependencies` in this repo would fix the issue for people?  I'm guessing that's where the bug lies.

**Comment by skratchdot** [comment]
I published a new version `1.0.6` to test if moving `jquery` to peerDependencies worked.

**Comment by richardlawrence** [comment]
I'm still having this issue with 1.0.6.

**Comment by katemont** [comment]
I'm also experiencing this with 1.0.6

**Comment by tim35050** [comment]
When I tried to install the module with JQuery 2.x already installed, it gave me a "The package jquery@2.1.4 does not satisfy its siblings' peerDependencies requirements!". I was able to install it after downgrading to JQuery 1.x. Now, I'm experiencing the same problem as others above (using 1.0.6).

**Comment by skratchdot** [comment]
Thanks @tim35050 . I'll try to take another look at this.  I'm guessing you are using webpack as well?

**Comment by tim35050** [comment]
@skratchdot yep. Thanks for all the hard work, looking forward to using this!

**Comment by LoicUV** [comment]
Same problem than @tim35050 but using browserify here.

**Comment by maorshabo** [comment]
Got the same problem as @tim35050, using Webpack and jQuery 2.x

**Comment by duanearnett** [comment]
Getting the same error with tests using Jest. 

````
TypeError: $this.$picker.daterangepicker is not a function
        at module.exports.React.createClass.componentDidMount (node_modules/react-bootstrap-daterangepicker/lib/index.js:54:17)
````

**Comment by cloudsan** [comment]
+1 as @duanearnett

**Comment by annelorraineuy** [comment]
Same error as well, using Webpack and jQuery 2.x :(

**Comment by holmancts** [comment]
I'm not sure what sequence results in this happening, but I was seeing this error in 1.0.6 and noticed that the bootstrap-daterangepicker nested dependency had its own jquery in it. When it require()s jquery it was getting that one, while react-bootstrap-daterangepicker was getting the top-level one and therefore it couldn't find the daterangepicker() function in either the window nor in $. I thought that by default all of the dependencies now get flattened out at the top level, so I am confused how it got there, but deleting that nested jquery and repacking fixed it  (I am using Browserify currently, but it should be the same fix for Webpack), and when I uninstalled and reinstalled react-bootstrap-daterangepicker, it did not regenerate this nested sub-dependency. Hope this helps someone else!

**Comment by seekshiva** [comment]
Thanks @holmancts . Had the same issues (using webpack).

So now, in the beginning of my script, I do, 
```
import $ from 'jquery'
window.$ = $
```
and removed the global jquery.

This way my script uses the same jQuery that the plugin did.

**Comment by njj** [comment]
I'm also getting this with Webpack and jquery@^2.2.0

**Comment by seekshiva** [comment]
@njj make it jquery@^1.12.0

**Comment by steveohmn** [comment]
I'm getting
`TypeError: $this.$picker.daterangepicker is not a function`
in my Firebug, when I'm trying to use it.

What should be done in `index.js` file to use this feature properly?

**Comment by steveohmn** [comment]
Where is `this.refs` referring to in `$this.$picker = $(this.refs.picker);` in https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/master/lib/index.js#L61 ?

**Comment by steveohmn** [comment]
Do you have to be using React@^0.14.0 ?
I have mine @^0.13.1 is that probably why? @skratchdot

**Comment by skratchdot** [comment]
the ref comes from here: https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/2a398ded90899d8ad2a820d4a3e9f114b0107771/lib/index.js#L79

Yes, I think the 0.13.1 is the issue.  You should be able to use an older version of this library to get the 13.1 support. I'll post a link in a bit.

btw- Sorry for not helping out with this project lately. I think the majority of the problems started when someone requested I start requiring the bootstrap-daterangepicker lib from npm rather than including it directly like I was originally (before the bootstrap-daterangepicker was ever published on npm). 

Now there seems to be some inconsistencies with the jQuery versions used.

**Comment by skratchdot** [comment]
Can you do me a favor and see if requiring `0.6.0` works for you? Do this by adding:
```
"react-bootstrap-daterangepicker": "0.6.0"
```
to your `package.json` file, then run `npm install`

**Comment by steveohmn** [comment]
It works, but UI is not very up-to-date as the latest version...
Is this because dependencies are out-dated right now?

![capture](https://cloud.githubusercontent.com/assets/4087365/12859190/613ed3de-cc09-11e5-9a03-62b6ed6d84c5.PNG)

**Comment by skratchdot** [comment]
Yes. probably need to download the css from that branch: 

https://github.com/skratchdot/react-bootstrap-daterangepicker/tree/0.6.0/css

**Comment by steveohmn** [comment]
Ok. I'll try now.
Thanks!

**Comment by SlowburnAZ** [comment]
Any updates on this?

**Comment by digicoffey** [comment]
I am also getting this error using webpack. I don't actually use jQuery for my project. Any luck figuring it out?

Thanks!

**Comment by steveohmn** [comment]
@digicoffey I tried using 0.6.0 version as @skratchdot has mentioned since I was using React@^0.13.1 for my development.
Maybe you should try using that? It solved the problem for me.

**Comment by SlowburnAZ** [comment]
@steveohmn @digicoffey I tried using 0.6.0, and it kinda worked...  the problem I was seeing with that version was that the calendars were reversed.  I would pick a range of dates, and the left-side calendar showed the date indicated in the right-side text box (the one above the calendars), and the right-side calendar showed the date indicated in the left-side text box.

I wish this bug could be squashed for the latest version.  I tried a number of things to no avail...

**Comment by steveohmn** [comment]
@SlowburnAZ I don't know why that occurs.. It worked for me. Did you install react-bootstrap in right version and included CSS file from the css directory?

It would also help if you provide the screenshot image also.

Thanks

**Comment by digicoffey** [comment]
@steveohmn Thanks for the info, much appreciated. I will give it a go, but I also hope we will be able to use the latest eventually. Not having the styles is not an issue for me.

@SlowburnAZ If I come across this issue and find out how to fix it I'll let you know, thanks.

**Comment by SlowburnAZ** [comment]
@steveohmn Hmmm...  I didn't alter the version for the "react-bootstrap" dependency, I only changed "react-bootstrap-daterangepicker" to 0.6.0.  I did use the right CSS file for 0.6.0, as referenced above.  If I in fact need a different version of the "react-bootstrap" dependency, which version should it be?

@digicoffey When I get home, I'll switch back to 0.6.0 again and get a screenshot posted.

**Comment by steveohmn** [comment]
@SlowburnAZ I used the "react-bootstrap" version in package.json file of "react-bootstrap-daterangepicker 0.6.0." which was found to be `"react-bootstrap": "^0.25.1"`

**Comment by SlowburnAZ** [comment]
@steveohmn @digicoffey So, I must not have had the right react-bootstrap version.  I tried again last night and things looked to be okay.

**Comment by debugpai** [comment]
Is there any way to make it work with react 0.14 and above? I'm getting the same issue and reverting to 0.6.0 is giving other problems like `this.startDate.format` is not a function

**Comment by steveohmn** [comment]
When I declare `getInitialState`, I use startDate and endDate to be defined.
After that I use `this.state.startDate.format('DD-MMM-YYYY');` to render the date to the format I want.
Maybe try defining the startDate in `getInitialState` and use the above format function to get desired output?

Thanks

**Comment by debugpai** [comment]
Turns out I was not passing moment date. Date string were working in a previous version I guess. Thanks a lot.

**Comment by snackycracky** [comment]
also having this issue when deploying to a remote server, locally this worked fine. please fix asap 👍

**Comment by snackycracky** [comment]
we are switching to a different datepicker now b/c 0.6.0 is not supporting isomorphic stuff + other issues.

**Comment by hale** [comment]
I was able to solve this by specifying more recent versions of node / npm / webpack (building on the server with `heroku-postbuild`)

```
 "engines": {
    "node": "4.1.2"
    "node": "6.3.0",
    "npm": "3.10.3"
  },
```

```
"webpack": "^1.13.1",
```

**Comment by skratchdot** [comment]
I'll try to publish a new version soon.  There have been a few merged PR's since the last publish.  I'll update dependencies as well.

**Comment by amPerl** [comment]
@skratchdot The new release fixed it for us, thanks!

**Comment by brendan-myers** [comment]
I'm getting this exact same error when we build on CircleCI. Locally - completely fine.

**Comment by phanhaiquang** [comment]
I am using webpack, and below setting in webpack.config.js fixed this issue

```
  externals: {
     jquery: 'var jQuery'
  },
```

**Comment by kimek** [comment]
@itaibaruch ask them two times to check if jquery wasn't included two times in page. i had same issue as one app.js had included jquery and in header I also had jQuery

**Comment by rbagai** [comment]
I am also getting this same issue while using react-bootstrap-daterangepicker with version 3.2.2 Is there any solution to the problem 'Uncaught TypeError: $this.$picker.daterangepicker is not a function'.

**Comment by TMonika** [comment]
Still facing the same issue with v3.2.2 and v2.0.0. On debugging, got to know jQuery is getting overridden at some point due to which even if bootstrap-daterangepicker is adding daterangepicker function to query it is not found. Any update on this?

**Comment by barbalex** [comment]
This is suddenly happening to me again too (I remember it happening earlier in the project development). I am using:

- react-bootstrap-daterangepicker: 3.4.1
- react-bootstrap: 0.32.1
- jquery: 3.3.1

**Comment by barbalex** [comment]
I now downgraded jquery to v3.2.1 and the error disappeared

**Comment by BossensM** [comment]
I suddenly got the same issue again. Changing jquery versions didn't help. Any ideas?

**Comment by barbalex** [comment]
After nuking node_modules and running `yarn` the error has re-appeared :-(

**Comment by RKushnir** [comment]
@barbalex make sure that you actually have jquery 3.2.1 installed and the version is locked in `package.json` and `yarn.lock`, so it cannot get accidentally updated.

**Comment by barbalex** [comment]
@RKushnir: Thanks for helping. jquery _was_ locked in yarn.lock.

After having this repeatedly happen over the past months, I gave up and migrated to react-datepicker.

**Comment by skratchdot** [comment]
@barbalex - Sorry about these issues.  I just don't have time to focus on fixing items (as this library was something I used early on- and don't currently use it- so can only help maintain it when I have spare time).  I need to put a list of alternatives in the readme.

**Comment by barbalex** [comment]
@scratchbot: Don't worry. And thank you a lot for building this tool. It helped me for quite a while. And I absolutely understand that you are not my slave and I am not paying you ;-)

**Comment by skratchdot** [comment]
@barbalex - it sucks that it causes people so many problems though :) Anyways, I think a good list of date pickers in the readme will help people out.

**Comment by skratchdot** [comment]
I added a few alternatives here: https://github.com/skratchdot/react-bootstrap-daterangepicker#other-react-date-pickers

**Comment by MarcoPortillo** [comment]
@barbalex I already tried this and is not working, what did you do? I have jquery 3.2.1, react-bootstrap 0.32.1 and react-bootstrap-daterangepicker 3.4.0 (been trying with lastest version, no luck)

react-datepicker does not work for me, I need a date range picker with time and predefined ranges as well :-)

**Comment by barbalex** [comment]
@MarcoPortillo Sorry, I have no experience with predefined ranges

**Comment by aashirMIQ** [comment]
@barbalex its working after reinstalling all dependencies by using npm rather yarn.

**Comment by mattgutoski** [comment]
For us this showed up recently with the new 3.5.0 jQuery update.  We found that jQuery was being included in our bundle twice. Once from our own dependencies, and once as a [transient dependency](https://github.com/dangrossman/daterangepicker/blob/master/package.json#L25)  from bootstrap-daterangepicker.

Depending on build process and how modules are installed/resolved... might determine if bootstrap-daterangepickers own node_module dependency is deduped or not. And might explain the various levels of success with reinstalling if:

1. your are enforcing a package-lock or `npm cli` (which dedupes)
2. using yarn which might flatten the dependency tree by other means
3. have some other external module resolution. eg. Webpack `alias: { 'jquery': path.join(nodeModulesPath, '/jquery/dist/jquery') }`

This might not be the root cause for everyone, but was for us. Hope it helps.

**Comment by skratchdot** [comment]
closing this due to inactivity. please re-open if this is still an issue in v6.0.0 or greater
