### ISSUE TITLE
have an error with new version

### ISSUE THREAD

**Issue by sonorx** [skratchdot/react-bootstrap-daterangepicker#41]
with dependencies:
"jquery": "~2.1.4",
    "react": "^0.14.0",
    "react-bootstrap-daterangepicker": "^1.0.1",
have an error: 
"Uncaught TypeError: $this.$picker.daterangepicker is not a function"

with old version:
    "jquery": "~2.1.4",
    "react": "^0.14.0",
    "react-bootstrap-daterangepicker": "^0.6.0",
all working fine, do you have any idea how to fix that?

**Comment by skratchdot** [comment]
@sonorx - I think jQuery ^1.11.3 is needed for react-bootstrap.  What other libs are you using?  Are you sure it worked with jquery 2.1.4 on the old version?  Have you done a `npm install` to make sure the versions you have locally are the versions you specified in package.json?

**Comment by sonorx** [comment]
yes, i'm sure that its working in old, and switching to 1.11.3 also not helping in new. shure I did npm install. what other libs?:) ok, thats all my dependencies: 
"dependencies": {
    "babel-runtime": "^5.8.20",
    "bootstrap": "^3.3.5",
    "bootstrap-datepicker": "^1.5.0",
    "classnames": "~2.2.0",
    "core-js": "^1.2.2",
    "css-loader": "~0.20.1",
    "flux": "^2.0.1",
    "font-awesome": "^4.3.0",
    "formsy-react": "^0.17.0",
    "humps": "1.0.0",
    "immutable": "~3.7.4",
    "invariant": "^2.0.0",
    "jquery": "~2.1.4",
    "keymirror": "^0.1.1",
    "lodash": "^3.10.1",
    "mixin": "^0.2.0",
    "moment": "^2.10.3",
    "node-polyglot": "^0.4.1",
    "normalizr": "^1.3.0",
    "phantomjs": "^1.9.18",
    "react": "^0.14.0",
    "react-addons-test-utils": "^0.14.0",
    "react-bootstrap": "~0.27.2",
    "react-bootstrap-daterangepicker": "^0.6.0",
    "react-date-picker": "^3.1.7",
    "react-dnd": "^2.0.0",
    "react-dnd-html5-backend": "^2.0.0",
    "react-dom": "^0.14.0",
    "react-loader": "^2.0.0",
    "react-mixin": "^3.0.0",
    "react-pure-render": "^1.0.1",
    "react-radio": "^1.0.6",
    "react-router": "^1.0.0-rc3",
    "react-select": "~0.7.0",
    "react-time-picker": "^1.0.7",
    "selectn": "^0.10.0",
    "shortid": "^2.2.4",
    "whatwg-fetch": "^0.10.0"
  },
  "devDependencies": {
    "babel-core": "^5.4.5",
    "babel-eslint": "^4.1.3",
    "babel-loader": "^5.0.0",
    "bower": "^1.6.3",
    "eslint": "^1.7.1",
    "eslint-loader": "^1.0.0",
    "eslint-plugin-react": "^3.6.2",
    "file-loader": "^0.8.4",
    "grunt": "~0.4.5",
    "grunt-cli": "^0.1.13",
    "grunt-contrib-clean": "~0.6.0",
    "grunt-contrib-compress": "~0.13.0",
    "grunt-contrib-connect": "~0.11.2",
    "grunt-contrib-copy": "~0.8.1",
    "grunt-karma": "~0.12.1",
    "grunt-open": "~0.2.3",
    "grunt-webpack": "~1.0.8",
    "jasmine": "^2.3.2",
    "jasmine-core": "^2.3.2",
    "jshint": "^2.8.0",
    "jshint-loader": "~0.8.3",
    "jsx-loader": "~0.13.2",
    "karma": "^0.13.11",
    "karma-chrome-launcher": "~0.2.1",
    "karma-cli": "^0.1.0",
    "karma-firefox-launcher": "~0.1.3",
    "karma-jasmine": "^0.3.5",
    "karma-phantomjs-launcher": "~0.2.1",
    "karma-phantomjs-shim": "^1.1.1",
    "karma-sourcemap-loader": "^0.3.5",
    "karma-script-launcher": "~0.1.0",
    "karma-webpack": "~1.7.0",
    "less": "^2.5.3",
    "less-loader": "^2.2.1",
    "load-grunt-tasks": "~3.3.0",
    "raw-loader": "^0.5.1",
    "react-hot-loader": "^1.2.8",
    "style-loader": "~0.12.4",
    "underscore": "~1.8.3",
    "url-loader": "~0.5.5",
    "webpack": "^1.10.1",
    "webpack-dev-server": "^1.12.1"
  }

**Comment by skratchdot** [comment]
@sonorx - I wasn't able to reproduce this locally (with the demo code here: https://github.com/skratchdot/react-bootstrap-daterangepicker/blob/master/demo/src/App.js).

I did `rm -rf ./node_modules/; npm install; gulp;` and the site was demo site was re-built.  I do remember seeing this error one time when using jQuery v2, but I even tried using the latest jQuery this time, and wasn't able to reproduce the error you are seeing.

Can you post the example `<DateRangePicker />` code you are using, or try re-installing with `"react-bootstrap-daterangepicker": "1.0.2"` ?

**Comment by sonorx** [comment]
with 1.0.2 still not working, I will try to cut reproducible code with error

**Comment by skratchdot** [comment]
@sonorx - Thanks for the report. I believe 1.0.3 should now fix the issue.  Someone else reported the same thing in #42.  I believe it's due to how a started requiring `npm install bootstrap-daterangepicker` as a dependency.  It started modifying window.jQuery at some point instead of the global jQuery...

**Comment by sonorx** [comment]
@skratchdot Unfortunately still not solved for me with new version...

**Comment by stevenwanderski** [comment]
Same problem here. Using `1.0.6`.

**Comment by jamiemccrindle** [comment]
I'm seeing the same issue with 1.0.6 too

**Comment by mychaelgo** [comment]
same issue with v 3.0.0. Any workaround?

**Comment by artemstorozhuk** [comment]
Same issue for me. Also [competitor's wrapper](https://github.com/luqin/react-bootstrap-datetimerangepicker) has same issue as well.
